"""add_hackathon_features

Revision ID: 0018b1c0e350
Revises: 9765a245204b
Create Date: 2026-07-15 12:35:23.192501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0018b1c0e350'
down_revision: Union[str, None] = '9765a245204b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_features',
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('registrations_enabled', sa.Boolean(), nullable=False),
    sa.Column('teams_enabled', sa.Boolean(), nullable=False),
    sa.Column('submissions_enabled', sa.Boolean(), nullable=False),
    sa.Column('judging_enabled', sa.Boolean(), nullable=False),
    sa.Column('leaderboard_enabled', sa.Boolean(), nullable=False),
    sa.Column('certificates_enabled', sa.Boolean(), nullable=False),
    sa.Column('announcements_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', name='uq_hackathon_features_hackathon_id')
    )
    op.create_unique_constraint('uq_team_member', 'team_members', ['team_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_member', 'team_members', type_='unique')
    op.drop_table('hackathon_features')
    # ### end Alembic commands ###