"""add_organization_and_hackathon

Revision ID: 3a09d48df96e
Revises: 6fab80cbbd75
Create Date: 2026-06-23 00:07:52.173471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a09d48df96e'
down_revision: Union[str, None] = '6fab80cbbd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('hackathons',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.Enum('online', 'offline', 'hybrid', name='hackathonmode'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'ongoing', 'ended', name='hackathonstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_open', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.Column('min_team_size', sa.Integer(), nullable=False),
    sa.Column('registration_mode', sa.Enum('open', 'approval', name='registrationmode'), nullable=False),
    sa.Column('website_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('prize_pool', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hackathons')
    op.drop_table('organizations')
    # ### end Alembic commands ###