"""add website_versions

Revision ID: 401b57c4c144
Revises: d0a4c7e2b981
Create Date: 2026-07-29 18:49:38.138147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '401b57c4c144'
down_revision: Union[str, None] = 'd0a4c7e2b981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_versions',
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('project', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'version', name='uq_website_version_number')
    )
    op.create_index('ix_website_versions_hackathon_version', 'website_versions', ['hackathon_id', 'version'], unique=False)
    op.create_index('ix_website_versions_published', 'website_versions', ['hackathon_id', 'is_published'], unique=False)
    # NOTE: autogenerate also wanted to drop custom_forms_slug_key and
    # form_attachments_answer_id_key. Those are pre-existing constraints on
    # unrelated tables that the models express differently; dropping them here
    # would let duplicate form slugs through. Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_website_versions_published', table_name='website_versions')
    op.drop_index('ix_website_versions_hackathon_version', table_name='website_versions')
    op.drop_table('website_versions')
    # ### end Alembic commands ###